# Generated by Django 4.2.30 on 2026-07-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_budget_category_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='imap_host',
            field=models.CharField(default='imap.gmail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='imap_password',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='imap_port',
            field=models.IntegerField(default=993),
        ),
        migrations.AddField(
            model_name='profile',
            name='imap_user',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='smtp_host',
            field=models.CharField(default='smtp.gmail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='smtp_port',
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name='profile',
            name='smtp_user',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
