# Generated by Django 4.2.30 on 2026-07-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_profile_imap_host_profile_imap_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auto_fetch_emails',
            field=models.BooleanField(default=True),
        ),
    ]
